controllers:
  resource: ../src/Core/Endpoints/Http/
  type: annotation

kernel:
  resource: ../src/Core/Kernel.php
  type: annotation

_errors:
  resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
  prefix: /_error
