core:
  resource: ../src/Core/Endpoints/Http/
  type: annotation

events_collector:
  resource: ../src/EventsCollector/Endpoints/Http/
  type: annotation

_errors:
  resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
  prefix: /_error
