---
services:
  app:
    build: .
    ports:
      - 8080:9000
    volumes:
      - ".:/app"
    working_dir: "/app"
    command:
      - php
      - -S
      - 0.0.0.0:9000
      - -t
      - "/app/public"
