# used for dev without mounting, ci-server for ex
---
version: "3.9"
services:
  app:
    build: .
    image: antonmarin/want2watch:latest
    ports:
      - "8080:9000"
    volumes:
      - "~/.composer/auth.json:/root/.composer/auth.json"
    working_dir: "/app"
    command: ["php", "-d", "zend_extension=xdebug.so",
              "-S", "0.0.0.0:9000", "-t", "/app/public"]
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      APP_GOOGLE_PROJECT_ID: "collector-346904"
      APP_GOOGLE_PRIVATE_KEY_ID: "d259a5243e310c0bd1d713749b0796eedf279cde"
      APP_GOOGLE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDoYHwBnuMPcgP5\n4fZAbYQO4dgkaGlRExoBqWS7XXSkxAy5rtcQjRxvbWwM097iJNH2cxnpnXspIVDN\nQX/8XQjGpbo/ZC0oeQ+V/DK3DhF1SbY6O0FY/HpY6+BmCiJGpgonG+vZL5oASfXA\n/OC5WF8mkAvfWsSHSH89PsvGWWYVg1CjDenJV/U/4R2ZdLL0HZomjtZlFRaDXrVY\n05eJA8l6uGmc7f34OzKiEc/23TjYZJj3RAX8gLtLbzVukf4NRDQHzK1Nrhvo8ilE\nyiIrAIOkXoUllt6SObEAV3J270EkQFhpKI2+gdMxKsNbyw1a8hTXEjwGDA0H7tM1\nH5Qd+RpDAgMBAAECggEARaozUwsOuGEulvnqqOsMNaf4dAXHWRJ4b/oYJGHCp+jM\nhdhISoJ7fV5ZD8lu3u458gAUyyg2taByyG40D/TWPjOOEBYYwbL1fLoUfDOgAUEd\ne/yqvSJIDaN9bSnpl7OMhKgGv2BZc2+42OgW+Qno0LdLj+T22TXfS32peqfvhk/6\n+9YahlLyPQ3svhC5ewVtGrNUb1bnmmUnYqFxDmBwYDkqq3iTxXTrOJTVUZBA7z2i\nrONFyM3i5ZTlxdTJLau86GMIwqu9iQuVlNkKxbg2Zj9gg4qcSoFPF8UtEGXegkuP\nJGyHNiRKfaBzaEzhvNOWtK5WG+0IMpTCrE5sbhYjUQKBgQD+aTRLARXVFj6GWXlP\n46LaqBiBy+AwRwYnLPJsgXJ05lRoeR91ghSzZN3jwWKEbITLd9bmuPuQ21Oa2Pcu\nvgKfU1uVMb24dobIZNnJPYhb5eZNwuEj2vGitrQiPZAHY6r/PZuL/i+TIWXxo+bJ\nsCkRniMJJv/fyNFLGFDZECR8swKBgQDp1AxdszqUpc43e24gHWZL3gQZB/5JTYCr\nhFi7ci7PV8ay681YHVTQqvhq525H8XCzNCDsKRSvSeNWU1rO3FKfZOCCPvgeboP4\nYLw9gNkPy8nvVSujBssoqkZ8Xhp50sxGjrecrZWp9gyPXJAmpBBte2/ohvcehYWH\n8TjcT+PUMQKBgH06Rb5Bq4B28ZHqCtezIh9lLKL/OrwoybOQ4UddtHwsQBIoxL5v\nqEbheIM6Vob+b6NDuulY1qNoAlAvSgSdDOdl/aeDk3JwDUoosjbnbe5mTKWsLmwa\nwmQocKSGDxZEDhCTP7R6CuruPqLh3aEbcCu23mIL61k5HSRMtMcTthIXAoGAd+uL\niAaidZfvgd7opMnPK/uqKFhEHr4DznMqur+dqDMBMcPjZVxtojL9An68vWLjBNUo\nSVXsSNXhJOXM/ahbK2omBkZbI+hUAG9EO1q4d/RxFTCeF5clXC6vxZrRg0cMAuew\n3UbdKfSJjoDPYTHlRvD2fM+zL1EVIZoiKkNCuhECgYBVfl5hL8CRDBHf5ClNJtj7\nSGig1Foetp8uoP8JWx8FdL+F3ywnhSEKPZrw1ZKH8xTLBUYbsZuyxmJzsv0ApxsH\nryRegMrFeoPJE9Cl5CJBxFGNYEKUGIeL5NoJ/bulb5/htvl+MuHzRhux9yS8m0O2\nENO9xfewMbD6U1GTlS761g==\n-----END PRIVATE KEY-----\n" # yamllint disable-line
      APP_GOOGLE_CLIENT_ID: "115162007451028805655"
      APP_GOOGLE_CLIENT_NAME: "test-30"
      FRAMEWORK_TEST: "false"
      GLIDE_PASS: |-
        $$2y$$13$$CKKFnANpn4L7KAk7o37OaujGNEpRk/4RbbCM3oB9PGCTiD5CNu1vi
      PHP_INI_XDEBUG_REMOTE_HOST: host.docker.internal
      PHP_IDE_CONFIG: serverName=want2watch
