# see https://symfony.com/doc/current/reference/configuration/framework.html
parameters:
  # no env substitution in framework config
  framework.test: '%env(bool:FRAMEWORK_TEST)%'

framework:
  csrf_protection: false
  default_locale: en
  form:
    enabled: false
  http_method_override: false
  php_errors:
    log: true
    throw: true
  property_access:
    magic_get: false
    magic_set: false
    throw_exception_on_invalid_index: true
  property_info:
    enabled: false
  router:
    # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
    # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
    #default_uri: http://localhost
    strict_requirements: null
    utf8: true
  secret: '%env(APP_SECRET)%'
  serializer:
    enabled: true
  session:
    enabled: false
  test: '%framework.test%'
  translator:
    enabled: false
  validation:
    enabled: true
