# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  router:
    strict_requirements: null
    utf8: true

    # Configure how to generate URLs in non-HTTP contexts, such as CLI commands.
    # See https://symfony.com/doc/current/routing.html#generating-urls-in-commands
    #default_uri: http://localhost
  secret: '%env(APP_SECRET)%'
  serializer:
    enabled: true
  session:
    enabled: false
  #  csrf_protection: true
  #http_method_override: true

  #esi: true
  #fragments: true
  php_errors:
    log: true
  #cache:
    # Unique name of your app: used to compute stable namespaces for cache keys.
    #prefix_seed: your_vendor_name/app_name

    # The "app" cache stores to the filesystem by default.
    # The data in this cache should persist between deploys.
    # Other options include:

    # Redis
    #app: cache.adapter.redis
    #default_redis_provider: redis://localhost

    # Namespaced pools use the above "app" backend by default
    #pools:
    #my.dedicated.cache: null
