# Domain services configuration here
# add more service definitions when explicit configuration is needed
# please note that last definitions always *replace* previous ones
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # make controllers available to inject services
  # this creates a service per class whose id is the fully-qualified class name
  EventsCollector\Endpoints\Http\:
    resource: '../Endpoints/Http/*'
    exclude: '../Endpoints/Http/**/{Request,Response*}.php'
    tags: [controller.service_arguments]
