services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  antonmarin\want2watch\Infrastructure\:
    resource: '../*'

  antonmarin\want2watch\Infrastructure\Http\OpenApiCodeGenerator\Command:
    arguments:
      - '%kernel.project_dir%/http/specification.yml'

  antonmarin\want2watch\Infrastructure\Http\OpenApiCodeGenerator\NetteGenerator:
    arguments:
      - '%kernel.project_dir%/src/Core/Endpoints/Http'
      - 'antonmarin\want2watch\Core\Endpoints\Http'

  antonmarin\want2watch\Infrastructure\Http\SymfonyHttpKernel\RequestDTOResolver:
    tags:
      - { name: controller.request_value_resolver, priority: 50 }

  logger.critical:
    class: Symfony\Component\HttpKernel\Log\Logger
    arguments:
      - !php/const Psr\Log\LogLevel::CRITICAL
  logger.notice:
    class: Symfony\Component\HttpKernel\Log\Logger
    arguments:
      - !php/const Psr\Log\LogLevel::NOTICE
  logger.info:
    class: Symfony\Component\HttpKernel\Log\Logger
    arguments:
      - !php/const Psr\Log\LogLevel::INFO
  logger.debug:
    class: Symfony\Component\HttpKernel\Log\Logger
    arguments:
      - !php/const Psr\Log\LogLevel::DEBUG
