### timestamp when the action was triggered
POST {{hostname}}/glide/wantieAdded
Content-Type: application/json
Accept: application/json

{
    "hookKind": "app-action",
    "appID": "applicationIdHere",
    "idempotencyKey": "uniqueWebhookIdHere",
    "timestamp": "2021-09-24T05:23:52.263Z",
    "params": {
        "wantieTitle": {
            "type": "string|number|boolean|date-time",
            "value": "Bulbasaur"
        }
    }
}

###
