---
openapi: "3.0.0"
info:
  title: want2watch
  version: 0.0.1
servers:
  - url: http://localhost:8080
paths:
  /:
    get:
      responses:
        200:
          description: OK

components:
  schemas:
    ErrorResponse:
      type: object
