name: Backend pipeline
on: 
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/**'
defaults:
  run:
    working-directory: backend
jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Pre-build validations
        run: make lint
      - name: Build application image
        run: make build
      - name: Post-build validations
        run: make validate-post-build
