name: Backend pipeline
on: 
  push:
    paths:
      - 'backend/**'
defaults:
  run:
    working-directory: backend
jobs:
  pre-build:
    name: pre build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Pre-build validations
        run: make lint
      
  post-build:
    name: post build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test
        run: make validate-post-build
