name: Backend pipeline
on: 
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
defaults:
  run:
    working-directory: backend
env:
  IMAGE_TAG: "antonmarin/want2watch:latest"
jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Pre-build validations
        run: make lint
      - name: Build application image
        run: make build
      - name: Post-build validations
        run: make test
      - name: Push image
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u antonmarin --password-stdin
          docker push $IMAGE_TAG
