name: Backend pipeline
on: 
  push:
    paths:
      - backend
defaults:
  run:
    working-directory: backend
jobs:
  integration-pipeline:
    name: Integration pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Pre-build validations
        run: make lint
      - name: Build
        run: make build
      - name: Test
        run: make test
