name: Backend pipeline
on: 
  push:
    paths:
      - 'backend/**'
defaults:
  run:
    working-directory: backend
jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Validations
        run: make lint build validate-post-build
