name: Validate github configuration
on: 
  push:
    paths:
      - '.github/workflows/**'
jobs:
  validate_workflows:
    name: Integration pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Not implemented
        run: echo "Not implemented yet!"
