name: Validate github configuration
on: 
  push:
    paths:
      - '.github/workflows/**'
jobs:
  validate_workflows:
    name: Integration pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: nwisbeta/validate-yaml-schema@v1.0.3
        with:
          yamlSchemasJson: |
            {
                "http://json.schemastore.org/github-workflow": ["/.github/workflow/*.yml", "/.github/workflow/*.yaml"]
            }
